### ISSUE TITLE
CRAN policy violations

### ISSUE THREAD

**Issue by chartgerink** [libscie/datr#9]
Need to fix these for CRAN submissions. Documenting here at the same time for others.

- [x] Thanks, please do not start your descriptiot with "This package", 
package name or similar.
- [x] Please write package names and software names in single quotes (e.g. 
'datr') in title and description.
- [x] Please add more small executable examples in your Rd-files.
- [x] Please ensure that your functions do not write by default or in your 
examples in the user's home filespace. That is not allow by CRAN 
policies. Please only write/save files if the user has specified a 
directory. In your examples you can write to tempdir().
- [x] Please fix and resubmit.

**Comment by chartgerink** [comment]
To be continued.... Just submitted it :+1:

**Comment by chartgerink** [comment]
```
Thanks, please add small executable (outside of \donttest{} or 
\dontrun{}) examples in your Rd-files. Examples like

   clone_dat(link = 'dat://a1b2c3...)

are not executable at all.

Please fix and resubmit.
```

I guess I should fix this but wonder how given that it seems contradictory to the [guidelines for examples in Rd files](https://developer.r-project.org/Rds.html).

**Comment by hrbrmstr** [comment]
To add to PR #10, consider doing something like https://github.com/tidyverse/ggplot2/blob/2184d962b2326ffab0cec4977b22795df004c149/R/stat-binhex.r#L45 which uses https://github.com/tidyverse/ggplot2/blob/f872279c6189be9fe24d924ef0ca5d7f10a04e64/R/utilities.r#L45 vs having `devtools` in `Imports:`. 

`devtools` is a _pretty big_ dependency: https://github.com/r-lib/devtools/blob/master/DESCRIPTION#L18 and while it's super-likely folks working with `dat` will also prbly already have `devtools` installed, you can make the package dependencies pretty much `0` if you take the `try_require()` route (since it's not 100% necessary to install `dat` via this pkg).

**Comment by chartgerink** [comment]
Sweet, thanks for this fantastic PR! I'll review it shortly :)

You just made sure this cheetah got petted. Look how happy they are :)
![](https://media.giphy.com/media/12Ip6BKWKEa1W0/giphy.gif)

**Comment by chartgerink** [comment]
So I will add a `utils.R` and [paste this in](https://github.com/tidyverse/ggplot2/blob/f872279c6189be9fe24d924ef0ca5d7f10a04e64/R/utilities.r#L45)

```R
try_require <- function(package, fun) {
  if (requireNamespace(package, quietly = TRUE)) {
    library(package, character.only = TRUE)
    return(invisible())
  }

  stop("Package `", package, "` required for `", fun , "`.\n",
    "Please install and try again.", call. = FALSE)
}
```

And include this in the `install_dat()`

```R
install_dat <- function (link, dir) {
  try_require('devtools', 'install')
  clone_dat(link, dir)

  install(dir)
  unlink(dir, recursive = TRUE)

  message('Successfully installed package from Dat network')
}
```

Just posting here for now because I am too lazy to put it in the code right away.
